info:
  component: Turbine
  
server:
  port: 8989

management:
  port: 8990
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/