info:
  component: Zuul Server
 
server:
  port: 8765

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    productcomposite:
      path: /productcomposite/**
#      stripPrefix: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO