info:
  component: Edge Server
  
server:
  port: 8765

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
 
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#If your Zuul server is also EurekaClient (use @EnableDiscoveryClient annotation) it will discover all the services and automatically will create routes.
#Ex. Zuul server is zuul.mydomain.com Eureka has 2 services registered with it : orders and accounts
#Then Zuul will automatically have two routes Zuul.mydomain.com/orders and Zuul.mydomain.com/accounts
#And this will forward to particular service. It will also automatically load balance calls for you if services run on multiple machines.
   
ribbon:
  eureka:
    enabled: true  
     

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO