info:
  component: Zuul Server
  
server:
  port: 8765

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
 
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: "*"
  routes:
    product-information-ribbon: 
      path: /ribbon-resttemplate/**
      service-id: product-information
      strip-prefix: false
    product-information-feign: 
      path: /feign-hystrix/**
      service-id: product-information
      strip-prefix: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO